// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NetCS.proto

package main

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetCSJoin_ID int32

const (
	NetCSJoin_PH    NetCSJoin_ID = 0
	NetCSJoin_CODE1 NetCSJoin_ID = 1
	NetCSJoin_CODE2 NetCSJoin_ID = 2
)

var NetCSJoin_ID_name = map[int32]string{
	0: "PH",
	1: "CODE1",
	2: "CODE2",
}

var NetCSJoin_ID_value = map[string]int32{
	"PH":    0,
	"CODE1": 1,
	"CODE2": 2,
}

func (x NetCSJoin_ID) String() string {
	return proto.EnumName(NetCSJoin_ID_name, int32(x))
}

func (NetCSJoin_ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{0, 0}
}

type NetSCJoin_ID int32

const (
	NetSCJoin_PH    NetSCJoin_ID = 0
	NetSCJoin_CODE1 NetSCJoin_ID = 2
	NetSCJoin_CODE2 NetSCJoin_ID = 1
)

var NetSCJoin_ID_name = map[int32]string{
	0: "PH",
	2: "CODE1",
	1: "CODE2",
}

var NetSCJoin_ID_value = map[string]int32{
	"PH":    0,
	"CODE1": 2,
	"CODE2": 1,
}

func (x NetSCJoin_ID) String() string {
	return proto.EnumName(NetSCJoin_ID_name, int32(x))
}

func (NetSCJoin_ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{1, 0}
}

type NetCSPing_ID int32

const (
	NetCSPing_PH    NetCSPing_ID = 0
	NetCSPing_CODE1 NetCSPing_ID = 2
	NetCSPing_CODE2 NetCSPing_ID = 3
)

var NetCSPing_ID_name = map[int32]string{
	0: "PH",
	2: "CODE1",
	3: "CODE2",
}

var NetCSPing_ID_value = map[string]int32{
	"PH":    0,
	"CODE1": 2,
	"CODE2": 3,
}

func (x NetCSPing_ID) String() string {
	return proto.EnumName(NetCSPing_ID_name, int32(x))
}

func (NetCSPing_ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{2, 0}
}

type NetCSPong_ID int32

const (
	NetCSPong_PH    NetCSPong_ID = 0
	NetCSPong_CODE1 NetCSPong_ID = 3
	NetCSPong_CODE2 NetCSPong_ID = 2
)

var NetCSPong_ID_name = map[int32]string{
	0: "PH",
	3: "CODE1",
	2: "CODE2",
}

var NetCSPong_ID_value = map[string]int32{
	"PH":    0,
	"CODE1": 3,
	"CODE2": 2,
}

func (x NetCSPong_ID) String() string {
	return proto.EnumName(NetCSPong_ID_name, int32(x))
}

func (NetCSPong_ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{3, 0}
}

type NetCSJoin struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetCSJoin) Reset()         { *m = NetCSJoin{} }
func (m *NetCSJoin) String() string { return proto.CompactTextString(m) }
func (*NetCSJoin) ProtoMessage()    {}
func (*NetCSJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{0}
}

func (m *NetCSJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetCSJoin.Unmarshal(m, b)
}
func (m *NetCSJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetCSJoin.Marshal(b, m, deterministic)
}
func (m *NetCSJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetCSJoin.Merge(m, src)
}
func (m *NetCSJoin) XXX_Size() int {
	return xxx_messageInfo_NetCSJoin.Size(m)
}
func (m *NetCSJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_NetCSJoin.DiscardUnknown(m)
}

var xxx_messageInfo_NetCSJoin proto.InternalMessageInfo

func (m *NetCSJoin) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type NetSCJoin struct {
	Resp                 string   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetSCJoin) Reset()         { *m = NetSCJoin{} }
func (m *NetSCJoin) String() string { return proto.CompactTextString(m) }
func (*NetSCJoin) ProtoMessage()    {}
func (*NetSCJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{1}
}

func (m *NetSCJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetSCJoin.Unmarshal(m, b)
}
func (m *NetSCJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetSCJoin.Marshal(b, m, deterministic)
}
func (m *NetSCJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetSCJoin.Merge(m, src)
}
func (m *NetSCJoin) XXX_Size() int {
	return xxx_messageInfo_NetSCJoin.Size(m)
}
func (m *NetSCJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_NetSCJoin.DiscardUnknown(m)
}

var xxx_messageInfo_NetSCJoin proto.InternalMessageInfo

func (m *NetSCJoin) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

type NetCSPing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetCSPing) Reset()         { *m = NetCSPing{} }
func (m *NetCSPing) String() string { return proto.CompactTextString(m) }
func (*NetCSPing) ProtoMessage()    {}
func (*NetCSPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{2}
}

func (m *NetCSPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetCSPing.Unmarshal(m, b)
}
func (m *NetCSPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetCSPing.Marshal(b, m, deterministic)
}
func (m *NetCSPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetCSPing.Merge(m, src)
}
func (m *NetCSPing) XXX_Size() int {
	return xxx_messageInfo_NetCSPing.Size(m)
}
func (m *NetCSPing) XXX_DiscardUnknown() {
	xxx_messageInfo_NetCSPing.DiscardUnknown(m)
}

var xxx_messageInfo_NetCSPing proto.InternalMessageInfo

type NetCSPong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetCSPong) Reset()         { *m = NetCSPong{} }
func (m *NetCSPong) String() string { return proto.CompactTextString(m) }
func (*NetCSPong) ProtoMessage()    {}
func (*NetCSPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_056c6b54b87af7c6, []int{3}
}

func (m *NetCSPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetCSPong.Unmarshal(m, b)
}
func (m *NetCSPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetCSPong.Marshal(b, m, deterministic)
}
func (m *NetCSPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetCSPong.Merge(m, src)
}
func (m *NetCSPong) XXX_Size() int {
	return xxx_messageInfo_NetCSPong.Size(m)
}
func (m *NetCSPong) XXX_DiscardUnknown() {
	xxx_messageInfo_NetCSPong.DiscardUnknown(m)
}

var xxx_messageInfo_NetCSPong proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("main.NetCSJoin_ID", NetCSJoin_ID_name, NetCSJoin_ID_value)
	proto.RegisterEnum("main.NetSCJoin_ID", NetSCJoin_ID_name, NetSCJoin_ID_value)
	proto.RegisterEnum("main.NetCSPing_ID", NetCSPing_ID_name, NetCSPing_ID_value)
	proto.RegisterEnum("main.NetCSPong_ID", NetCSPong_ID_name, NetCSPong_ID_value)
	proto.RegisterType((*NetCSJoin)(nil), "main.NetCSJoin")
	proto.RegisterType((*NetSCJoin)(nil), "main.NetSCJoin")
	proto.RegisterType((*NetCSPing)(nil), "main.NetCSPing")
	proto.RegisterType((*NetCSPong)(nil), "main.NetCSPong")
}

func init() { proto.RegisterFile("NetCS.proto", fileDescriptor_056c6b54b87af7c6) }

var fileDescriptor_056c6b54b87af7c6 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf6, 0x4b, 0x2d, 0x71,
	0x0e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x72, 0xe4,
	0xe2, 0x04, 0x0b, 0x7a, 0xe5, 0x67, 0xe6, 0x09, 0x09, 0x70, 0x31, 0x17, 0xa5, 0x16, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a, 0x4a, 0x5c, 0x4c, 0x9e, 0x2e, 0x42, 0x6c, 0x5c,
	0x4c, 0x01, 0x1e, 0x02, 0x0c, 0x42, 0x9c, 0x5c, 0xac, 0xce, 0xfe, 0x2e, 0xae, 0x86, 0x02, 0x8c,
	0x30, 0xa6, 0x91, 0x00, 0x93, 0x92, 0x33, 0xd8, 0x88, 0x60, 0x67, 0xb0, 0x11, 0x42, 0x5c, 0x2c,
	0x45, 0xa9, 0xc5, 0x05, 0x50, 0x33, 0xc0, 0x6c, 0x5c, 0x86, 0x30, 0x21, 0x0c, 0x61, 0x54, 0xd2,
	0x87, 0xba, 0x23, 0x20, 0x33, 0x2f, 0x9d, 0x08, 0x0d, 0xcc, 0x08, 0x0d, 0xf9, 0xb8, 0x35, 0x30,
	0x23, 0x39, 0x33, 0x89, 0x0d, 0xec, 0x6d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x0c,
	0xf5, 0x36, 0x05, 0x01, 0x00, 0x00,
}
