// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CS.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CSJoin struct {
	CODE1                int32    `protobuf:"varint,1,opt,name=CODE1,proto3" json:"CODE1,omitempty"`
	CODE2                int32    `protobuf:"varint,2,opt,name=CODE2,proto3" json:"CODE2,omitempty"`
	Req                  string   `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSJoin) Reset()         { *m = CSJoin{} }
func (m *CSJoin) String() string { return proto.CompactTextString(m) }
func (*CSJoin) ProtoMessage()    {}
func (*CSJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee8a77b5bd8375c, []int{0}
}

func (m *CSJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSJoin.Unmarshal(m, b)
}
func (m *CSJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSJoin.Marshal(b, m, deterministic)
}
func (m *CSJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSJoin.Merge(m, src)
}
func (m *CSJoin) XXX_Size() int {
	return xxx_messageInfo_CSJoin.Size(m)
}
func (m *CSJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_CSJoin.DiscardUnknown(m)
}

var xxx_messageInfo_CSJoin proto.InternalMessageInfo

func (m *CSJoin) GetCODE1() int32 {
	if m != nil {
		return m.CODE1
	}
	return 0
}

func (m *CSJoin) GetCODE2() int32 {
	if m != nil {
		return m.CODE2
	}
	return 0
}

func (m *CSJoin) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type SCJoin struct {
	CODE1                int32    `protobuf:"varint,1,opt,name=CODE1,proto3" json:"CODE1,omitempty"`
	CODE2                int32    `protobuf:"varint,2,opt,name=CODE2,proto3" json:"CODE2,omitempty"`
	Resp                 string   `protobuf:"bytes,3,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCJoin) Reset()         { *m = SCJoin{} }
func (m *SCJoin) String() string { return proto.CompactTextString(m) }
func (*SCJoin) ProtoMessage()    {}
func (*SCJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee8a77b5bd8375c, []int{1}
}

func (m *SCJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCJoin.Unmarshal(m, b)
}
func (m *SCJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCJoin.Marshal(b, m, deterministic)
}
func (m *SCJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCJoin.Merge(m, src)
}
func (m *SCJoin) XXX_Size() int {
	return xxx_messageInfo_SCJoin.Size(m)
}
func (m *SCJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_SCJoin.DiscardUnknown(m)
}

var xxx_messageInfo_SCJoin proto.InternalMessageInfo

func (m *SCJoin) GetCODE1() int32 {
	if m != nil {
		return m.CODE1
	}
	return 0
}

func (m *SCJoin) GetCODE2() int32 {
	if m != nil {
		return m.CODE2
	}
	return 0
}

func (m *SCJoin) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

func init() {
	proto.RegisterType((*CSJoin)(nil), "message.CSJoin")
	proto.RegisterType((*SCJoin)(nil), "message.SCJoin")
}

func init() { proto.RegisterFile("CS.proto", fileDescriptor_6ee8a77b5bd8375c) }

var fileDescriptor_6ee8a77b5bd8375c = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x70, 0x0e, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x72, 0xe3,
	0x62, 0x73, 0x0e, 0xf6, 0xca, 0xcf, 0xcc, 0x13, 0x12, 0xe1, 0x62, 0x75, 0xf6, 0x77, 0x71, 0x35,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x60, 0xa2, 0x46, 0x12, 0x4c, 0x08, 0x51,
	0x23, 0x21, 0x01, 0x2e, 0xe6, 0xa2, 0xd4, 0x42, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10,
	0x53, 0xc9, 0x83, 0x8b, 0x2d, 0xd8, 0x99, 0x64, 0x73, 0x84, 0xb8, 0x58, 0x8a, 0x52, 0x8b, 0x0b,
	0xa0, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x17, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9d,
	0x86, 0x7a, 0xae, 0xad, 0x00, 0x00, 0x00,
}
